version: '2'
services:
  postgresql:
    container_name: postgresql
    image: docker.io/bitnami/postgresql:latest
    restart: unless-stopped
    environment:
      ALLOW_EMPTY_PASSWORD: yes
      POSTGRESQL_USERNAME: bn_keycloak
      POSTGRESQL_DATABASE: bitnami_keycloak
    volumes:
      - 'postgresql_data:/bitnami/postgresql'     
  keycloak:
    container_name: keycloak
    image: docker.io/bitnami/keycloak:latest
    ports:
      - 443:8443
    environment:
      KEYCLOAK_CREATE_ADMIN_USER: true
      KEYCLOAK_ADMIN: #<admin-login>
      KEYCLOAK_ADMIN_PASSWORD: #<admin-password>
      KEYCLOAK_ENABLE_HTTPS: true    
      KEYCLOAK_HTTPS_USE_PEM: true
      KEYCLOAK_PRODUCTION: true
      KEYCLOAK_HTTPS_CERTIFICATE_FILE: '/opt/bitnami/keycloak/certs/chain.pem'
      KEYCLOAK_HTTPS_CERTIFICATE_KEY_FILE: '/opt/bitnami/keycloak/certs/key.pem'
    volumes:
      - './ssl/chain.pem:/opt/bitnami/keycloak/certs/chain.pem'
      - './ssl/key.pem:/opt/bitnami/keycloak/certs/key.pem'
    depends_on:
      - postgresql
  pgadmin4:
      container_name: pgadmin4
      image: dpage/pgadmin4    
      ports:
          - 5053:443
      volumes:
          - './ssl/chain.pem:/certs/server.cert'
          - './ssl/key.pem:/certs/server.key'
          - './pgadmin/servers.json:/pgadmin4/servers.json'
      environment:
          - PGADMIN_DEFAULT_EMAIL=#<admin@example.com>
          - PGADMIN_DEFAULT_PASSWORD=#<admin-password>
          - PGADMIN_ENABLE_TLS=True
volumes:
  postgresql_data:
    driver: local
